/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    employees: Employee;
    media: Media;
    messages: Message;
    occupations: Occupation;
    pages: Page;
    pricing: Pricing;
    'pricing-features': PricingFeature;
    programs: Program;
    'quick-news': QuickNew;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    employees: EmployeesSelect<false> | EmployeesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    occupations: OccupationsSelect<false> | OccupationsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    pricing: PricingSelect<false> | PricingSelect<true>;
    'pricing-features': PricingFeaturesSelect<false> | PricingFeaturesSelect<true>;
    programs: ProgramsSelect<false> | ProgramsSelect<true>;
    'quick-news': QuickNewsSelect<false> | QuickNewsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'contact-details': ContactDetail;
    footer: Footer;
    settings: Setting;
  };
  globalsSelect: {
    'contact-details': ContactDetailsSelect<false> | ContactDetailsSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employees".
 */
export interface Employee {
  id: number;
  avatar?: (number | null) | Media;
  fullName: string;
  email: string;
  phoneNumber: string;
  occupation: number | Occupation;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occupations".
 */
export interface Occupation {
  id: number;
  name: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  personalData: {
    fullName: string;
    email: string;
    phoneNumber: string;
  };
  subject: string;
  message: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  /**
   * Enabling this option displays breadcrumbs on the page.
   */
  isBreadcrumbsVisible?: boolean | null;
  /**
   * The URL-friendly identifier for this page. Example: "about-us" → fitvive.com/about-us
   */
  slug: string;
  /**
   * Manage metadata for search engines and social media sharing.
   */
  meta?: {
    /**
     * Displayed as the page title in search engine results and browser tabs. Keep it clear, relevant, and under ~60 characters.
     */
    title?: string | null;
    /**
     * A short summary of the page shown below the title in search results. Aim to attract clicks. Recommended length: up to ~160 characters.
     */
    description?: string | null;
    /**
     * Image used when sharing the page on social platforms like Facebook or LinkedIn. Recommended size: 1200×630px.
     */
    thumbnail?: (number | null) | Media;
    /**
     * Optional. Comma-separated keywords relevant to the page (e.g. “web development, react, e-commerce”).
     */
    keywords?: string | null;
  };
  /**
   * The main title of the page, typically used in the H1 heading and for identifying the page content.
   */
  pageTitle: string;
  /**
   * Build the page layout by adding and arranging predefined content blocks.
   */
  layout?:
    | (
        | {
            header: {
              chipLabel?: string | null;
              title: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              description?: string | null;
            };
            isContactDetailsEnabled?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'CONTACT_FORM';
          }
        | {
            header: {
              chipLabel?: string | null;
              title: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              description?: string | null;
            };
            employees?: (number | Employee)[] | null;
            redirectButton?: RedirectButton;
            id?: string | null;
            blockName?: string | null;
            blockType: 'EMPLOYEES';
          }
        | {
            header: {
              chipLabel?: string | null;
              title: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              description?: string | null;
            };
            faq?:
              | {
                  question: string;
                  answer: {
                    root: {
                      type: string;
                      children: {
                        type: string;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'FAQ';
          }
        | {
            header: {
              chipLabel?: string | null;
              title: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              description?: string | null;
            };
            links?:
              | {
                  /**
                   * The text that will appear as the clickable label for this link.
                   */
                  label: string;
                  /**
                   * Select whether this link points to an internal page or an external website.
                   */
                  type: 'internal' | 'external';
                  internalLink?: (number | null) | Page;
                  /**
                   * Full external URL, e.g. https://example.com
                   */
                  externalLink?: string | null;
                  id?: string | null;
                }[]
              | null;
            image?: (number | null) | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'HERO';
          }
        | ProgramsBlock
        | {
            header: {
              chipLabel?: string | null;
              title: {
                root: {
                  type: string;
                  children: {
                    type: string;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              };
              description?: string | null;
            };
            subscriptions?: (number | Pricing)[] | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'SUBSCRIPTION';
          }
        | {
            quickNews: (number | QuickNew)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'QUICK_NEWS_MARQUEE';
          }
      )[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RedirectButton".
 */
export interface RedirectButton {
  label?: string | null;
  page?: (number | null) | Page;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProgramsBlock".
 */
export interface ProgramsBlock {
  header: {
    chipLabel?: string | null;
    title: {
      root: {
        type: string;
        children: {
          type: string;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    };
    description?: string | null;
  };
  programs: (number | Program)[];
  id?: string | null;
  blockName?: string | null;
  blockType: 'PROGRAMS';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs".
 */
export interface Program {
  id: number;
  icon: number | Media;
  title: string;
  description: string;
  page?: (number | null) | Page;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing".
 */
export interface Pricing {
  id: number;
  isRecommended?: boolean | null;
  icon: number | Media;
  title: string;
  description: string;
  prices: {
    monthly: number;
    yearly: number;
  };
  features: (number | PricingFeature)[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-features".
 */
export interface PricingFeature {
  id: number;
  title: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quick-news".
 */
export interface QuickNew {
  id: number;
  /**
   * The text that will appear as the clickable label for this link.
   */
  label: string;
  /**
   * Select whether this link points to an internal page or an external website.
   */
  type: 'internal' | 'external';
  internalLink?: (number | null) | Page;
  /**
   * Full external URL, e.g. https://example.com
   */
  externalLink?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'employees';
        value: number | Employee;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'occupations';
        value: number | Occupation;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'pricing';
        value: number | Pricing;
      } | null)
    | ({
        relationTo: 'pricing-features';
        value: number | PricingFeature;
      } | null)
    | ({
        relationTo: 'programs';
        value: number | Program;
      } | null)
    | ({
        relationTo: 'quick-news';
        value: number | QuickNew;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "employees_select".
 */
export interface EmployeesSelect<T extends boolean = true> {
  avatar?: T;
  fullName?: T;
  email?: T;
  phoneNumber?: T;
  occupation?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  personalData?:
    | T
    | {
        fullName?: T;
        email?: T;
        phoneNumber?: T;
      };
  subject?: T;
  message?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "occupations_select".
 */
export interface OccupationsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  isBreadcrumbsVisible?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        thumbnail?: T;
        keywords?: T;
      };
  pageTitle?: T;
  layout?:
    | T
    | {
        CONTACT_FORM?:
          | T
          | {
              header?:
                | T
                | {
                    chipLabel?: T;
                    title?: T;
                    description?: T;
                  };
              isContactDetailsEnabled?: T;
              id?: T;
              blockName?: T;
            };
        EMPLOYEES?:
          | T
          | {
              header?:
                | T
                | {
                    chipLabel?: T;
                    title?: T;
                    description?: T;
                  };
              employees?: T;
              redirectButton?: T | RedirectButtonSelect<T>;
              id?: T;
              blockName?: T;
            };
        FAQ?:
          | T
          | {
              header?:
                | T
                | {
                    chipLabel?: T;
                    title?: T;
                    description?: T;
                  };
              faq?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        HERO?:
          | T
          | {
              header?:
                | T
                | {
                    chipLabel?: T;
                    title?: T;
                    description?: T;
                  };
              links?:
                | T
                | {
                    label?: T;
                    type?: T;
                    internalLink?: T;
                    externalLink?: T;
                    id?: T;
                  };
              image?: T;
              id?: T;
              blockName?: T;
            };
        PROGRAMS?: T | ProgramsBlockSelect<T>;
        SUBSCRIPTION?:
          | T
          | {
              header?:
                | T
                | {
                    chipLabel?: T;
                    title?: T;
                    description?: T;
                  };
              subscriptions?: T;
              id?: T;
              blockName?: T;
            };
        QUICK_NEWS_MARQUEE?:
          | T
          | {
              quickNews?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "RedirectButton_select".
 */
export interface RedirectButtonSelect<T extends boolean = true> {
  label?: T;
  page?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ProgramsBlock_select".
 */
export interface ProgramsBlockSelect<T extends boolean = true> {
  header?:
    | T
    | {
        chipLabel?: T;
        title?: T;
        description?: T;
      };
  programs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing_select".
 */
export interface PricingSelect<T extends boolean = true> {
  isRecommended?: T;
  icon?: T;
  title?: T;
  description?: T;
  prices?:
    | T
    | {
        monthly?: T;
        yearly?: T;
      };
  features?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pricing-features_select".
 */
export interface PricingFeaturesSelect<T extends boolean = true> {
  title?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programs_select".
 */
export interface ProgramsSelect<T extends boolean = true> {
  icon?: T;
  title?: T;
  description?: T;
  page?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "quick-news_select".
 */
export interface QuickNewsSelect<T extends boolean = true> {
  label?: T;
  type?: T;
  internalLink?: T;
  externalLink?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-details".
 */
export interface ContactDetail {
  id: number;
  /**
   * List of components for defining contact methods f.e. e-mail address
   */
  contactItems?:
    | {
        label: string;
        value: string;
        type: 'clock' | 'envelope' | 'marker' | 'phone';
        id?: string | null;
      }[]
    | null;
  socialMedia?: {
    facebook?: string | null;
    instagram?: string | null;
    x?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  /**
   * Text displayed above the footer.
   */
  motto?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Tagline placed below the logo.
   */
  catchphrase?: string | null;
  /**
   * Defines the quick links displayed in the website footer. Each link can be either an internal page reference or an external URL, along with a display label.
   */
  quickLinks?:
    | {
        /**
         * The text that will appear as the clickable label for this link.
         */
        label: string;
        /**
         * Select whether this link points to an internal page or an external website.
         */
        type: 'internal' | 'external';
        internalLink?: (number | null) | Page;
        /**
         * Full external URL, e.g. https://example.com
         */
        externalLink?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Defines the main navigation links displayed in the website header. Each link can be either an internal page reference or an external URL, along with a display label.
   */
  primaryNavigation?:
    | {
        /**
         * The text that will appear as the clickable label for this link.
         */
        label: string;
        /**
         * Select whether this link points to an internal page or an external website.
         */
        type: 'internal' | 'external';
        internalLink?: (number | null) | Page;
        /**
         * Full external URL, e.g. https://example.com
         */
        externalLink?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-details_select".
 */
export interface ContactDetailsSelect<T extends boolean = true> {
  contactItems?:
    | T
    | {
        label?: T;
        value?: T;
        type?: T;
        id?: T;
      };
  socialMedia?:
    | T
    | {
        facebook?: T;
        instagram?: T;
        x?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  motto?: T;
  catchphrase?: T;
  quickLinks?:
    | T
    | {
        label?: T;
        type?: T;
        internalLink?: T;
        externalLink?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  primaryNavigation?:
    | T
    | {
        label?: T;
        type?: T;
        internalLink?: T;
        externalLink?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}