export const BLOCK_TYPE = {
  CONTACT_FORM: 'CONTACT_FORM',
  EMPLOYEES: 'EMPLOYEES',
  FAQ: 'FAQ',
  HERO: 'HERO',
  PROGRAMS: 'PROGRAMS',
  SUBSCRIPTION: 'SUBSCRIPTION',
  QUICK_NEWS_MARQUEE: 'QUICK_NEWS_MARQUEE'
};
